#!/bin/bash

# Demo script showing bot picture URL format
echo "NHRL Bot Picture URL Examples"
echo "============================="
echo ""
echo "The bot picture API provides two formats:"
echo "1. Thumbnail (smaller, faster loading)"
echo "2. Full size (higher resolution)"
echo ""
echo "URL Format:"
echo "Thumbnail: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=BOT_NAME&thumb"
echo "Full size: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=BOT_NAME"
echo ""
echo "Examples:"
echo "---------"
echo ""
echo "Bot: Overlord"
echo "Thumbnail: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=Overlord&thumb"
echo "Full size: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=Overlord"
echo ""
echo "Bot: Death Roll (spaces converted to underscores)"
echo "Thumbnail: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=Death_Roll&thumb"
echo "Full size: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=Death_Roll"
echo ""
echo "Bot: Bloodsport"
echo "Thumbnail: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=Bloodsport&thumb"
echo "Full size: https://brettzone.nhrl.io/brettZone/getBotPic.php?bot=Bloodsport"
echo ""
echo "You can test these URLs directly in your browser!"
echo ""
echo "The new functionality automatically includes these URLs when:"
echo "- Using the 'get_bot_picture_url' operation"
echo "- Getting tournament data (players are enriched with picture URLs)"
echo "- Getting live fight stats (both bots get picture URLs)" 